### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by dkaskgkdua** [dkaskgkdua/dkaskgkdua#4]
![linux](https://user-images.githubusercontent.com/56568571/107945749-6cdae700-6fd3-11eb-9051-b7377068e5b6.png)

**Comment by ffffaaasl** [comment]
> 
>

**Comment by ffffaaasl** [comment]
[linux](https://user-images.githubusercontent.com/56568571/107945749-6cdae700-6fd3-11eb-9051-b7377068e5b6.png)
